
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 86400000
server:
#  端口
  port: 22222
spring:
  application:
    name: java-server
  datasource:
##   数据库链接地址
#    url: jdbc:mysql://202.194.14.120:3306/java_db?allowPublicKeyRetrieval=true&useSSL=false
###    数据库用户名
#    username: java_server
###    数据库密码
#    password: JavaServer2025@
    url: jdbc:mysql://202.194.14.120:3306/java_1_16?allowPublicKeyRetrieval=true&useSSL=false
    username: java_1_16
    password: JavaP116@
  jpa:
    generate-ddl: true
#    自动更新数据库表的结构
    hibernate.ddl-auto: update
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  jmx:
    enabled:false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
attach:
  folder: /teach-2025/
logging:
  config: classpath:loggback.xml

